################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
platform/zoul/remote-revb \
platform/zoul/remote-reva \
platform/zoul/firefly-reva \
platform/zoul/firefly \
platform/zoul/dev \
platform/zoul \
platform/z1 \
platform/z1/dev \
platform/z1/apps \
platform/wismote \
platform/wismote/dev \
platform/wismote/apps \
platform/win32/loader \
platform/win32/ctk \
platform/win32 \
platform/win32/cfs \
platform/stm32test \
platform/stm32nucleo-spirit1 \
platform/stm32nucleo-spirit1/stm32cube-lib/stm32cube-prj/Src \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/x_nucleo_iks01a1 \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/x_nucleo_ids01ax \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/stm32l1xx_nucleo \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/spirit1/src \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/sensors/lsm6ds3 \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/sensors/lsm6ds0 \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/sensors/lps25hb \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/sensors/lps25h \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/sensors/lis3mdl \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/sensors/hts221 \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/STM32L1xx_HAL_Driver/Src \
platform/stm32nucleo-spirit1/stm32cube-lib/drivers/CMSIS \
platform/stm32nucleo-spirit1/dev \
platform/srf06-cc26xx/srf06 \
platform/srf06-cc26xx/sensortag \
platform/srf06-cc26xx/sensortag/cc2650 \
platform/srf06-cc26xx/launchpad \
platform/srf06-cc26xx \
platform/srf06-cc26xx/common \
platform/sky \
platform/sky/dev \
platform/sky/apps \
platform/seedeye \
platform/seedeye/dev \
platform/seedeye/dev/mrf24j40 \
platform/openmote-cc2538/dev \
platform/openmote-cc2538 \
platform/nrf52dk/rtt \
platform/nrf52dk/dev \
platform/nrf52dk/dbg-io \
platform/nrf52dk \
platform/native/dev \
platform/native/ctk \
platform/native \
platform/minimal-net \
platform/micaz \
platform/micaz/dev \
platform/micaz/dev/sensors \
platform/micaz/apps/mts310 \
platform/micaz/apps \
platform/mbxxx/dev \
platform/mbxxx \
platform/mbxxx/apps \
platform/jn516x/lib \
platform/jn516x/dev \
platform/jn516x/dev/dr1199 \
platform/jn516x/dev/dr1175 \
platform/jn516x/dev/dr1174 \
platform/jn516x/dev/dongle \
platform/jn516x \
platform/galileo \
platform/galileo/net \
platform/galileo/drivers \
platform/galileo/core/sys \
platform/exp5438 \
platform/eval-adf7xxxmb4z \
platform/ev-aducrf101mkxz \
platform/econotag \
platform/econotag/apps/flash \
platform/econotag/apps/ecc \
platform/cooja-ip64 \
platform/cooja/testapps \
platform/cooja/sys \
platform/cooja \
platform/cooja/net \
platform/cooja/lib \
platform/cooja/dev \
platform/cooja/cfs \
platform/cc2538dk/dev \
platform/cc2538dk \
platform/cc2530dk \
platform/cc2530dk/dev \
platform/c64/lib \
platform/c64 \
platform/c128/lib \
platform/c128 \
platform/avr-zigbit \
platform/avr-rss2 \
platform/avr-rss2/dev \
platform/avr-rss2/apps/sniffer \
platform/avr-rcb \
platform/avr-ravenusb \
platform/avr-ravenlcd \
platform/avr-raven \
platform/avr-raven/apps/raven-webserver \
platform/avr-raven/apps/raven-lcd-interface \
platform/avr-raven/apps/raven-ipso \
platform/avr-atmega128rfa1 \
platform/avr-atmega128rfa1/apps/raven-webserver \
platform/avr-atmega128rfa1/apps/raven-lcd-interface \
platform/avr-atmega128rfa1/apps/raven-ipso \
platform/atarixl/lib \
platform/atarixl \
platform/apple2enh/sys \
platform/apple2enh/lib \
platform/apple2enh \
dev/sht11 \
dev/enc28j60 \
dev/ds2411 \
dev/cc2520 \
dev/cc2420 \
dev/cc1200 \
core/sys \
core/net/rpl \
core/net/rime \
core/net \
core/net/mac/tsch \
core/net/mac/sicslowmac \
core/net/mac \
core/net/mac/cxmac \
core/net/mac/contikimac \
core/net/llsec \
core/net/llsec/noncoresec \
core/net/ipv6 \
core/net/ipv6/multicast \
core/net/ipv4 \
core/net/ip64 \
core/net/ip \
core/net/http-socket \
core/loader \
core/lib \
core/lib/strncasecmp \
core/dev \
core/ctk/libconio \
core/ctk \
core/cfs \
. \

